// Generated 09 Mar 2023 09:03 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Delivery
{
    [Serializable]
    public class Delivery
     : MEBusinessBase<Delivery>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> DeliveryIDProperty = RegisterProperty<int>(c => c.DeliveryID, "ID", 0);
        /// <summary>
        /// Gets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key]
        public int DeliveryID
        {
            get { return GetProperty(DeliveryIDProperty); }
        }

        public static PropertyInfo<int> BasketIDProperty = RegisterProperty<int>(c => c.BasketID, "Basket", 0);
        /// <summary>
        /// Gets and sets the Basket value
        /// </summary>
        [Display(Name = "Basket", Description = ""),
        Required(ErrorMessage = "Basket required")]
        public int BasketID
        {
            get { return GetProperty(BasketIDProperty); }
            set { SetProperty(BasketIDProperty, value); }
        }   

        public static PropertyInfo<String> DeliveryOptionProperty = RegisterProperty<String>(c => c.DeliveryOption, "Delivery Option", "");
        /// <summary>
        /// Gets and sets the Delivery Option value
        /// </summary>
        [Display(Name = "Delivery Option", Description = "")]
        public String DeliveryOption
        {
            get { return GetProperty(DeliveryOptionProperty); }
            set { SetProperty(DeliveryOptionProperty, value); }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(DeliveryIDProperty);
        }

        public override string ToString()
        {
            if (this.DeliveryOption.Length == 0)
            {
                if (this.IsNew)
                {
                    return String.Format("New {0}", "Delivery");
                }
                else
                {
                    return String.Format("Blank {0}", "Delivery");
                }
            }
            else
            {
                return this.DeliveryOption;
            }
        }

        #endregion

        #endregion

        #region " Validation Rules "

        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
        }

        #endregion

        #region " Data Access & Factory Methods "

        protected override void OnCreate()
        {
            // This is called when a new object is created
            // Set any variables here, not in the constructor or NewDelivery() method.
        }

        public static Delivery NewDelivery()
        {
            return DataPortal.CreateChild<Delivery>();
        }

        public Delivery()
        {
            MarkAsChild();
        }

        internal static Delivery GetDelivery(SafeDataReader dr)
        {
            var d = new Delivery();
            d.Fetch(dr);
            return d;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            using (BypassPropertyChecks)
            {
                int i = 0;
                LoadProperty(DeliveryIDProperty, sdr.GetInt32(i++));
                LoadProperty(BasketIDProperty, sdr.GetInt32(i++));
                LoadProperty(DeliveryOptionProperty, sdr.GetString(i++));
            }

            MarkAsChild();
            MarkOld();
            BusinessRules.CheckRules();
        }

        protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
        {
            AddPrimaryKeyParam(cm, DeliveryIDProperty);

            cm.Parameters.AddWithValue("@BasketID", GetProperty(BasketIDProperty));
            cm.Parameters.AddWithValue("@DeliveryOption", GetProperty(DeliveryOptionProperty));

            return (scm) =>
            {
    // Post Save
    if (this.IsNew)
                {
                    LoadProperty(DeliveryIDProperty, scm.Parameters["@DeliveryID"].Value);
                }
            };
        }

        protected override void SaveChildren()
        {
            // No Children
        }

        protected override void SetupDeleteCommand(SqlCommand cm)
        {
            cm.Parameters.AddWithValue("@DeliveryID", GetProperty(DeliveryIDProperty));
        }

        #endregion

    }

}