// Generated 27 Feb 2023 08:59 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.RO
{
    [Serializable]
    public class ROCategoryList
     : MEReadOnlyListBase<ROCategoryList, ROCategory>
    {
        #region " Business Methods "

        public ROCategory GetItem(int CategoryID)
        {
            foreach (ROCategory child in this)
            {
                if (child.CategoryID == CategoryID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Categorys";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static ROCategoryList NewROCategoryList()
        {
            return new ROCategoryList();
        }

        public ROCategoryList()
        {
            // must have parameter-less constructor
        }

        public static ROCategoryList GetROCategoryList()
        {
            return DataPortal.Fetch<ROCategoryList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            this.IsReadOnly = false;
            while (sdr.Read())
            {
                this.Add(ROCategory.GetROCategory(sdr));
            }
            this.IsReadOnly = true;
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getROCategoryList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}