// Generated 16 Feb 2023 16:18 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.RO
{
    [Serializable]
    public class ROProduct
     : MEReadOnlyBase<ROProduct>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> ProductIDProperty = RegisterProperty<int>(c => c.ProductID, "ID", 0);
        /// <summary>
        /// Gets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key]
        public int ProductID
        {
            get { return GetProperty(ProductIDProperty); }
        }

        public static PropertyInfo<String> ProductNameProperty = RegisterProperty<String>(c => c.ProductName, "Product Name", "");
        /// <summary>
        /// Gets the Product Name value
        /// </summary>
        [Display(Name = "Product Name", Description = "")]
        public String ProductName
        {
            get { return GetProperty(ProductNameProperty); }
        }

        public static PropertyInfo<String> ProductDescriptionProperty = RegisterProperty<String>(c => c.ProductDescription, "Product Description", "");
        /// <summary>
        /// Gets the Product Description value
        /// </summary>
        [Display(Name = "Product Description", Description = "")]
        public String ProductDescription
        {
            get { return GetProperty(ProductDescriptionProperty); }
        }

        public static PropertyInfo<Decimal> ProductPriceProperty = RegisterProperty<Decimal>(c => c.ProductPrice, "Product Price", 0D);
        /// <summary>
        /// Gets the Product Price value
        /// </summary>
        [Display(Name = "Product Price", Description = "")]
        public Decimal ProductPrice
        {
            get { return GetProperty(ProductPriceProperty); }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(ProductIDProperty);
        }

        public override string ToString()
        {
            return this.ProductName;
        }

        #endregion

        #endregion

        #region " Data Access & Factory Methods "

        internal static ROProduct GetROProduct(SafeDataReader dr)
        {
            var r = new ROProduct();
            r.Fetch(dr);
            return r;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            int i = 0;
            LoadProperty(ProductIDProperty, sdr.GetInt32(i++));
            LoadProperty(ProductNameProperty, sdr.GetString(i++));
            LoadProperty(ProductDescriptionProperty, sdr.GetString(i++));
            LoadProperty(ProductPriceProperty, sdr.GetDecimal(i++));
        }

        #endregion

    }

}